### ISSUE TITLE
Mejorar el CSS

### ISSUE THREAD

**Issue by Losnen** [ULL-ESIT-GRADOII-TFG/samuel-ramos-tfg#11]

**Comment by crguezl** [comment]
Cuando se pone el ratón sobre las opciones de la barra (p.ej. sign-out), la opción deja de ser visible debido a la combinación de colores

**Comment by crguezl** [comment]
Ya no ocurre que Ccuando se pone el ratón sobre las opciones de la barra (p.ej. sign-out), la opción deja de ser visible debido a la combinación de colores
