### ISSUE TITLE
Empezamos a usar code-lab en producción

### ISSUE THREAD

**Issue by crguezl** [ULL-ESIT-GRADOII-TFG/samuel-ramos-tfg#17]
Voy a empezar a poner la práctica con CodeLab.
@Losnen, te voy informando

**Comment by crguezl** [comment]
Al enlace generado:

https://codelab-tfg1718.herokuapp.com/assigninvitation/ULL-ESIT-PL-1718Egg-Peg

le falta el slash `/`

**Comment by Losnen** [comment]
Los bugs que me ha comentado los arreglé y acabode pushear la nueva versión a [Heroku](https://codelab-tfg1718.herokuapp.com/)

**Comment by crguezl** [comment]
Sigue pasando lo mismo.  Este es el enlace que produce:

https://codelab-tfg1718.herokuapp.com/assigninvitation/ULL-ESIT-PL-1718egg-pegg

**Comment by crguezl** [comment]
Mira en: https://codelab-tfg1718.herokuapp.com/classroom/ULL-ESIT-PL-1718

**Comment by crguezl** [comment]
OK. He entrado como alumno y lo hace bien.  Debe ser que solo lo hace al profesor

**Comment by crguezl** [comment]
Como alumno cuando cliqueo en la URL https://codelab-tfg1718.herokuapp.com/assigninvitation/ULL-ESIT-PL-1718/egg-pegg entro a la vista de aceptación de la asignación

**Comment by crguezl** [comment]
Muchas gracias! :+1: ¡A por el slash /!

**Comment by crguezl** [comment]
Lo del  problema del slash sigue aún. Entiendo que a ti no te ocurre?

**Comment by Losnen** [comment]
Estoy revisando a ver si falta en algún lugar pero en principio no veo el error

**Comment by Losnen** [comment]
Vale, acabo de detectar el error, estaba un poco escondido, acabo de comitear y subir a [Heroku](https://codelab-tfg1718.herokuapp.com/)

**Comment by crguezl** [comment]
👌   Abierta la práctica para el alumnado. Empezamos

https://campusvirtual.ull.es/1718/mod/assign/view.php?id=200375
