### ISSUE TITLE
crea los repos publicos pese a que deberian ser privados

### ISSUE THREAD

**Issue by crguezl** [ULL-ESIT-GRADOII-TFG/samuel-ramos-tfg#20]
crea los repos publicos pese a que deberian ser privados @Losnen

**Comment by Losnen** [comment]
Me pongo con ello.

**Comment by Losnen** [comment]
Creo que el error está solucionado, no puedo probarlo porque no tengo un plan para organizaciones, el error era que una variable se asignaba mal en la base de datos. 

Si puede probarlo y me avisa que tal va.

**Comment by crguezl** [comment]
Hola Samuel,


Te he promovido a owner de https://github.com/orgs/ULL-ESIT-PL-1718/



2018-04-28 12:52 GMT+01:00 Samuel Ramos Barroso <notifications@github.com>:

**Comment by crguezl** [comment]
Efectivamente. Parece haberse arreglado, el repo para el alu ficticio se ha creado privado

**Comment by crguezl** [comment]
:+1:
